### ISSUE TITLE
split_libraries_fastq.py mapping file validation fails when validate_mapping_file doesn't

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1400]
```
$ split_libraries_fastq.py -i /home/caporaso/analysis/2014.01.16-butteryfly/Hcydno_R1.fastq.gz,/home/caporaso/analysis/2014.01.16-butteryfly/Ppoly_R1.fastq.gz,/home/caporaso/analysis/2014.01.16-butteryfly/Hcydno_R2.fastq.gz,/home/caporaso/analysis/2014.01.16-butteryfly/Ppoly_R2.fastq.gz --sample_id Hcydno.R1,Ppoly.R1,Hcydno.R2,Ppoly.R2 -o /home/caporaso/analysis/2014.01.16-butteryfly/slout_test/ -m /home/caporaso/analysis/2014.01.16-butteryfly/map-test.txt --barcode_type 'not-barcoded'
Traceback (most recent call last):
  File "/home/caporaso/code/qiime/scripts/split_libraries_fastq.py", line 364, in <module>
    main()
  File "/home/caporaso/code/qiime/scripts/split_libraries_fastq.py", line 276, in main
    None)
  File "/home/caporaso/code/qiime/qiime/split_libraries.py", line 314, in check_map
    'identify problems.')
ValueError: Errors were found with mapping file, please run validate_mapping_file.py to identify problems.

caporaso@bacon 12:32:57 2014.01.16-butteryfly$ validate_mapping_file.py -m /home/caporaso/analysis/2014.01.16-butteryfly/map-test.txt -o cid/
No errors or warnings were found in mapping file.
```

**Comment by yysmile2014** [comment]
Hey, I have exactly the same problem. How did you solve it actually? Could you tell it in detail?

**Comment by gregcaporaso** [comment]
@yysmile2014, are you using QIIME 1.9.0? If so, and you have the same use case that I mention above, you can call ``split_libraries_fastq.py`` without the ``-m`` option. This is a new feature in QIIME 1.9.0, so that specific fix won't work in earlier versions.
