### ISSUE TITLE
differential_abundance.py bug/doc fixes

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1813]
The following changes need to be made to differential_abundance.py prior to the 1.9.0 release:

- [x] when passing a category via `-c` that isn't in the mapping file, an uninformative error message is produced:

```
differential_abundance.py -i otu_table.biom -o DE_OTUs.txt -m map.txt -a metagenomeSeq_fitZIG -c not-real -x Control -y Fast
Traceback (most recent call last):
 File "/Users/caporaso/.virtualenvs/qiime/bin/differential_abundance.py", line 10, in <module>
   execfile(__file__)
 File "/Users/caporaso/Dropbox/code/Qiime/scripts/differential_abundance.py", line 88, in <module>
   main()
 File "/Users/caporaso/Dropbox/code/Qiime/scripts/differential_abundance.py", line 73, in main
   DA_fitZIG(input_path, out_path, mapping_fp, mapping_category, subcategory_1, subcategory_2)
 File "/Users/caporaso/Dropbox/code/Qiime/qiime/differential_abundance.py", line 32, in DA_fitZIG
   run_fitZIG(json_infile, out_path, mapping_category, subcategory_1, subcategory_2)
 File "/Users/caporaso/Dropbox/code/Qiime/qiime/differential_abundance.py", line 69, in run_fitZIG
   app_result = rsl(command_args=command_args, script_name='fitZIG.r')
 File "/Users/caporaso/Dropbox/code/Qiime/qiime/util.py", line 2006, in __call__
   % (''.join(open(errfilepath, 'r').readlines())))
burrito.util.ApplicationError: Unacceptable application exit status: 1, command: cd "/Users/caporaso/Dropbox/code/Qiime/qiime_test_data/differential_abundance/";  R --slave --args --source_dir /Users/caporaso/Dropbox/code/Qiime/qiime/support_files/R -i otu_table_json.biom -o DE_OTUs.txt -c not-real -x Control -y Fast  < /Users/caporaso/Dropbox/code/Qiime/qiime/support_files/R/fitZIG.r Program output:

Warning messages:
1: package ‘metagenomeSeq’ was built under R version 3.1.2
2: package ‘BiocGenerics’ was built under R version 3.1.2
3: package ‘RColorBrewer’ was built under R version 3.1.2
Error in `[.data.frame`(pData(MGS), , mapping_category) :
 undefined columns selected
Calls: fitZIG -> which -> %in% -> match -> [ -> [.data.frame
In addition: Warning message:
In cumNormStat(MGS) : Low quantile estimate. Default value being used.
Execution halted
```

- [x] when passing an invalid category value via `-x` or `-y`, the script doesn't error out and produces a statistics file with results that look somewhat valid

- [x] it would help to break up the script description into paragraphs b/c it's currently hard to read

@sowe9385 can you please work on this? We'll need this to be ready for the January 6th deadline @gregcaporaso mentioned in #1810.

@gregcaporaso and I will continue adding to this list (we're still testing out this new script).

cc @antgonza

**Comment by jairideout** [comment]
Fixed in #1820
