### ISSUE TITLE
fix AMI test failures

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1836]
Most are due to usearch, sfffile, sffinfo, and torque (meaning they're ok, since these binaries aren't included in our AMIs). The ones that are not related to these are:

```bash
$ Testing /home/ubuntu/temp/qiime-master/tests/test_otu_significance.py:

...

======================================================================
FAIL: test_run_correlation_test (__main__.GroupedCorrelationTests)
Test run_correlation_test works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/temp/qiime-master/tests/test_otu_significance.py", line 892, in test_run_correlation_test
    assert_almost_equal(obs_pvals[-1], 0.54600000000000004)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 490, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.54700000000000004
 DESIRED: 0.546

----------------------------------------------------------------------
Ran 15 tests in 12.121s

FAILED (failures=1)


Testing /home/ubuntu/temp/qiime-master/tests/test_parallel/test_identify_chimeric_seqs.py:

...

======================================================================
FAIL: test_parallel_chimeric_sequence_identifier_chimera_slayer (__main__.ParallelChimericSequenceIdentifierTests)
Test ParallelChimericSequenceIdentifier using ChimeraSlayer.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/temp/qiime-master/tests/test_parallel/test_identify_chimeric_seqs.py", line 123, in test_parallel_chimeric_sequence_identifier_chimera_slayer
    self.assertEqual(len(results), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 2 tests in 70.832s

FAILED (failures=1)

Testing /home/ubuntu/temp/qiime-master/tests/test_rarefaction.py:

...

======================================================================
ERROR: test_rarefy_to_files (__main__.FunctionTests)
rarefy_to_files should write valid files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/temp/qiime-master/tests/test_rarefaction.py", line 108, in test_rarefy_to_files
    include_lineages=False)
  File "/usr/local/lib/python2.7/dist-packages/qiime/rarefaction.py", line 123, in rarefy_to_files
    self._write_rarefaction(depth, rep, sub_otu_table)
  File "/usr/local/lib/python2.7/dist-packages/qiime/rarefaction.py", line 159, in _write_rarefaction
    write_biom_table(sub_otu_table, fname)
  File "/usr/local/lib/python2.7/dist-packages/qiime/util.py", line 556, in write_biom_table
    biom_table.to_hdf5(biom_file, generated_by, compress)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3481, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3361, in axis_dump
    compression=compression)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 99, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 114, in make_new_dset
    sid = h5s.create_simple(shape, maxshape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2362)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/tmp/pip-build-8Ijz6u/h5py/h5py/h5s.c:1353)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

======================================================================
ERROR: test_rarefy_to_files2 (__main__.FunctionTests)
rarefy_to_files should write valid files with some metadata on otus
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/temp/qiime-master/tests/test_rarefaction.py", line 127, in test_rarefy_to_files2
    include_lineages=False)
  File "/usr/local/lib/python2.7/dist-packages/qiime/rarefaction.py", line 123, in rarefy_to_files
    self._write_rarefaction(depth, rep, sub_otu_table)
  File "/usr/local/lib/python2.7/dist-packages/qiime/rarefaction.py", line 159, in _write_rarefaction
    write_biom_table(sub_otu_table, fname)
  File "/usr/local/lib/python2.7/dist-packages/qiime/util.py", line 556, in write_biom_table
    biom_table.to_hdf5(biom_file, generated_by, compress)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3481, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3361, in axis_dump
    compression=compression)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 99, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 114, in make_new_dset
    sid = h5s.create_simple(shape, maxshape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2362)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/tmp/pip-build-8Ijz6u/h5py/h5py/h5s.c:1353)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

----------------------------------------------------------------------
Ran 6 tests in 1.270s

FAILED (errors=2)


```

@wasade, @ElDeveloper, @josenavas, have you seen the h5py-related rarefaction error before?

**Comment by ElDeveloper** [comment]
@gregcaporaso, I don't recall seeing it before. Can you post the output
of print_qiime_config.py -ft ...

**Comment by gregcaporaso** [comment]
Here you go:

```
System information
==================
         Platform:	linux2
   Python version:	2.7.3 (default, Aug  1 2012, 05:14:39)  [GCC 4.6.3]
Python executable:	/usr/bin/python

QIIME default reference information
===================================
For details on what files are used as QIIME's default references, see here:
 https://github.com/biocore/qiime-default-reference/releases/tag/0.1.1

Dependency versions
===================
                QIIME library version:	1.9.0-rc1
                 QIIME script version:	1.9.0-rc1
      qiime-default-reference version:	0.1.1
                        NumPy version:	1.9.1
                        SciPy version:	0.14.1
                       pandas version:	0.15.2
                   matplotlib version:	1.4.2
                  biom-format version:	2.1.2
                         h5py version:	2.4.0 (HDF5 version: 1.8.4)
                         qcli version:	0.1.1
                         pyqi version:	0.3.2
                   scikit-bio version:	0.2.2
                       PyNAST version:	1.2.2
                      Emperor version:	0.9.5
                      burrito version:	0.9.0
             burrito-fillings version:	Installed.
                    sortmerna version:	SortMeRNA version 2.0, 29/11/2014
                    sumaclust version:	SUMACLUST Version 1.0.00
                                gdata:	Installed.
RDP Classifier version (if installed):	rdp_classifier-2.2.jar
          Java version (if installed):	1.6.0_33

QIIME config values
===================
For definitions of these settings and to learn how to configure QIIME, see here:
 http://qiime.org/install/qiime_config.html
 http://qiime.org/tutorials/parallel_qiime.html

                     blastmat_dir:	/qiime_software/blast-2.2.22-release/data
      pick_otus_reference_seqs_fp:	/usr/local/lib/python2.7/dist-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                         sc_queue:	all.q
      topiaryexplorer_project_dir:	None
     pynast_template_alignment_fp:	/usr/local/lib/python2.7/dist-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.fasta
                  cluster_jobs_fp:	start_parallel_jobs.py
pynast_template_alignment_blastdb:	None
assign_taxonomy_reference_seqs_fp:	/usr/local/lib/python2.7/dist-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                     torque_queue:	friendlyq
                    jobs_to_start:	1
            denoiser_min_per_core:	50
assign_taxonomy_id_to_taxonomy_fp:	/usr/local/lib/python2.7/dist-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
                         temp_dir:	/home/ubuntu/temp/
                     slurm_memory:	None
                      slurm_queue:	None
                      blastall_fp:	/qiime_software/blast-2.2.22-release/bin/blastall
                 seconds_to_sleep:	1

QIIME full install test results
===============================
..........................F
======================================================================
FAIL: test_usearch_supported_version (__main__.QIIMEDependencyFull)
usearch is in path and version is supported
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 640, in test_usearch_supported_version
    "which components of QIIME you plan to use.")
AssertionError: usearch not found. This may or may not be a problem depending on which components of QIIME you plan to use.

----------------------------------------------------------------------
Ran 27 tests in 0.480s

FAILED (failures=1)
```

**Comment by jairideout** [comment]
The first failure (`test_otu_significance.py`) looks like a regression -- this was previously reported in #1347 and fixed in #1364. The fix was then removed [here](https://github.com/biocore/qiime/commit/e2e7a52bb0285a51f2ba15f03bfd345b8192846d#diff-4fd85a3eccce7d847302b5ec21b8e72fL870). I'll issue a pull request shortly with a fix for this one.

**Comment by jairideout** [comment]
The second failure (`test_identify_chimeric_seqs.py`) is due to the new default `pynast_template_alignment_fp` -- we're now using 85% OTUs instead of the core set. Jenkins has been testing with the core set instead of the new default, which is why we haven't seen this failure before. I'll work on updating qiime-deploy (part of #1802) to create the correct QIIME config that uses the new defaults.

Not sure about the last two failures related to HDF5.

**Comment by ElDeveloper** [comment]
Thanks for sending that @gregcaporaso. It seems like it could possibly
be the HDF5 libraries version, my installation is using 1.8.12, the
Jenkins-AMI is using 1.8.13 (and these failures are not present in
either of those installations) and the new AMI is using 1.8.4.

**Comment by jairideout** [comment]
Thanks @ElDeveloper, this turned out to be the case. h5py supports HDF5 1.8.4 and later, but it seems that HDF5 1.8.4 isn't able to write datasets with a dimension of zero (i.e., `shape=(0,)`). The failing rarefaction tests are creating rarefied BIOM tables that are empty (i.e., rarefying at a depth of zero); these tables are 4x3 but are 100% sparse (NNZ=0). This causes an error to be raised with HDF5 1.8.4 when writing the BIOM table, but this doesn't happen with newer versions (I tested with 1.8.13 and 1.8.14).

@gregcaporaso and I think that this behavior, while undesirable, isn't a blocking bug because users are unlikely to create empty tables in practice ("empty" in this context means a table that only contains zeros). Even if a user were to create an empty table, it isn't likely to be useful for any further analysis. Finally, the error is noisy: in the unlikely event that a user posts this error message on the forum, we'll be able to explain what caused it.

It looks like BIOM is supposed to raise an error if it encounters an empty table during rarefaction (see [this line](https://github.com/biocore/qiime/blob/master/qiime/rarefaction.py#L173)). There's a discrepancy in the BIOM docs on what an empty table is though. @gregcaporaso created two issues on the BIOM issue tracker with more details:

https://github.com/biocore/biom-format/issues/581
https://github.com/biocore/biom-format/issues/582

I think the solution for now is to modify these two tests to not rarefy at a depth of zero (thus avoiding the empty table case). I'll issue a pull request for this shortly.

cc @wasade @Jorge-C @josenavas @adamrp

**Comment by gregcaporaso** [comment]
These issues have all been fixed and tested on the AMI. We're re-running the tests and will open a new issue if there are other test failures.

**Comment by ElDeveloper** [comment]
Great, thanks for the information! This seems like a reasonable
strategy.
