### ISSUE TITLE
observation_metadata_correlation.py script usage test failure if h5py isn't installed

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1856]
If h5py/HDF5 isn't installed, the following script usage tests fail for observation_metadata_correlation.py:

```
Testing 2 usage examples from: /usr/local/bin/observation_metadata_correlation.py
Running tests in: /home/ubuntu/temp/script_usage_tests/observation_metadata_correlation
Tests:
/usr/local/bin/observation_metadata_correlation.py -i otu_table.biom -m map.txt -c pH -s spearman -o spearman_otu_gradient.txt: Failed
Stdout:

Stderr:
Traceback (most recent call last):
  File "/usr/local/bin/observation_metadata_correlation.py", line 238, in <module>
    main()
  File "/usr/local/bin/observation_metadata_correlation.py", line 175, in main
    bt = load_table(opts.otu_table_fp)
  File "/usr/local/lib/python2.7/dist-packages/biom/parse.py", line 553, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: otu_table.biom does not appear to be a BIOM file!


/usr/local/bin/observation_metadata_correlation.py -i otu_table.biom -m map.txt -c pH -s pearson --pval_assignment_method bootstrapped --permutations 100 -o pearson_bootstrapped.txt: Failed
Stdout:

Stderr:
Traceback (most recent call last):
  File "/usr/local/bin/observation_metadata_correlation.py", line 238, in <module>
    main()
  File "/usr/local/bin/observation_metadata_correlation.py", line 175, in main
    bt = load_table(opts.otu_table_fp)
  File "/usr/local/lib/python2.7/dist-packages/biom/parse.py", line 553, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: otu_table.biom does not appear to be a BIOM file!
```

**Comment by ElDeveloper** [comment]
The solution in this case to replace the test file so it is a JSON file
instead of an HDF5 file. Should that be the policy for all the script
usage tests?

**Comment by jairideout** [comment]
Yep, that's what I did in #1854. I think this was the only HDF5 BIOM file under `qiime_test_data`. :+1: for keeping only JSON BIOM files under `qiime_test_data`.

**Comment by ElDeveloper** [comment]
Got it and agree, completely missed #1854.
