### ISSUE TITLE
make_otu_heatmap.py will fail when there's no metadata

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#1906]
If you pass in a table that doesn't have observation metadata, the following error will be raised:

```
make_otu_heatmap.py -i plel.hdf5.biom -o lolmap-test 
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/bin/make_otu_heatmap.py", line 10, in <module>
    execfile(__file__)
  File "/Users/yoshikivazquezbaeza/git_sw/qiime/scripts/make_otu_heatmap.py", line 256, in <module>
    main()
  File "/Users/yoshikivazquezbaeza/git_sw/qiime/scripts/make_otu_heatmap.py", line 160, in main
    obs_md_0 = obs_md[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by gregcaporaso** [comment]
@ElDeveloper, is this happening with the current dev version of biom (after the two issues in #1894 were fixed)?

**Comment by ElDeveloper** [comment]
@gregcaporaso, yes with the latest version of biom.
