### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by bwawrik** [biocore/qiime#1969]
Hi,

I'm trying to run qiime out of a docker. Everything installed well and seems to work great until I get to aligning my sequences.  I run the following command :

$ align_seqs.py -i rep_set.fna -t Silva_108/core_aligned/Silva_108_core_aligned_seqs.fasta -o pynast_aligned

I use an older version of Silva to keep the memory footprint small.  The files work fine on the qiime virtual box that I typically run on my desktop.

Here is the error I get:

Traceback (most recent call last):
  File "/usr/local/bin/align_seqs.py", line 211, in <module>
    main()
  File "/usr/local/bin/align_seqs.py", line 194, in main
    log_path=log_path, failure_path=failure_path)
  File "/usr/local/lib/python2.7/dist-packages/qiime/align_seqs.py", line 266, in __call__
    temp_dir=get_qiime_temp_dir())
  File "/usr/local/lib/python2.7/dist-packages/pynast/util.py", line 812, in pynast_seqs
    for seq, status in pynast_iterator:
  File "/usr/local/lib/python2.7/dist-packages/pynast/util.py", line 707, in ipynast_seqs
    Sequence(seq=template_alignment[template_seq_id],moltype=DNA)
  File "/usr/local/lib/python2.7/dist-packages/skbio/alignment/_alignment.py", line 248, in __getitem__
    return self.get_seq(index)
  File "/usr/local/lib/python2.7/dist-packages/skbio/alignment/_alignment.py", line 515, in get_seq
    return self[self._id_to_index[id]]
KeyError: 'DQ811862.1.1495 Bacteria;Chloroflexi;Caldilineae;Caldilineales;Caldilineaceae;uncultured;uncultured Chloroflexi bacterium'

Any thoughts what this error means ?
Thanks in advance !
Boris

**Comment by jairideout** [comment]
Can you please post your question on the QIIME forum? See http://help.qiime.org for instructions on getting help with QIIME.

**Comment by bwawrik** [comment]
Figured it out a while back. This was actually an out of memory error.

**Comment by alfbenpa** [comment]
I recently had a similar issue when I tried to use the aling_seqs.py function with updated silva.seed.v138.aln file. I solved it by modifying the headers in the .aln file and only leaving the identifiers (removing the taxonomy description and other information contained in the header).
Good luck!
Alfonso
