### ISSUE TITLE
align_seqs.py assumes pynast is installed

### ISSUE THREAD

**Issue by adamrp** [biocore/qiime#2008]
The [`min_percent_id`](https://github.com/biocore/qiime/blob/master/scripts/align_seqs.py#L110-L114) option is only added if pynast is installed, but on [lines 148-149](https://github.com/biocore/qiime/blob/master/scripts/align_seqs.py#L148-L149) the option is assumed to exist.

I noticed this problem while attempting to run pick_open_reference_otus.py with -m sortmerna_sumaclust using this command:
```
pick_open_reference_otus.py -i ERP005362.fna -o ERP005362_open_ref_gg_13_8_sortmerna -m sortmerna_sumaclust -p open_params.txt
```
and the params file contained:
```
pick_otus:threads	32
pick_otus:sortmerna_db	/Users/adro2179/gg_13_8_97_otus.idx
```

**Comment by gregcaporaso** [comment]
@adamrp, can you post the error that you got from this?

**Comment by gregcaporaso** [comment]
I'm going to remove this from the milestone - it's not really a big issue anymore now that we recommend installing with ``pip``, as PyNAST is always installed in that case as part of the base install.

**Comment by adamrp** [comment]
@gregcaporaso sorry for the delay. You can replicate this error by not having pynast installed, and then:
```
(python276)adam:align_seqs@master$ pwd
/Users/adam/git/qiime/qiime_test_data/align_seqs
(python276)adam:align_seqs@master$ align_seqs.py -i unaligned.fna 
Traceback (most recent call last):
  File "/Users/adam/git/qiime/scripts/align_seqs.py", line 211, in <module>
    main()
  File "/Users/adam/git/qiime/scripts/align_seqs.py", line 148, in main
    if opts.min_percent_id <= 1.0:
AttributeError: Values instance has no attribute 'min_percent_id'
```
