### ISSUE TITLE
Problem parsing mapping file in supervised_learning.py

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiime#2013]
I'm having a bit of a problem running `supervised_learning.py` - it seems that R is having a hard time parsing the mapping file.

Here's the error message below.
```
supervised_learning.py -i data/otu_table.json -m data/combined_mapping.txt -c BODY_SITE -o results -f
Traceback (most recent call last):
  File "/Users/mortonyt/.virtualenvs/qiime/bin/supervised_learning.py", line 5, in <module>
    pkg_resources.run_script('qiime==1.8.0-dev', 'supervised_learning.py')
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/qiime-1.8.0_dev-py2.7.egg/EGG-INFO/scripts/supervised_learning.py", line 255, in <module>
    main()
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/qiime-1.8.0_dev-py2.7.egg/EGG-INFO/scripts/supervised_learning.py", line 196, in main
    ntree, errortype, output_dir, verbose)
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/qiime-1.8.0_dev-py2.7.egg/qiime/supervised_learning.py", line 64, in run_supervised_learning
    app_result = rsl(predictor_fp)
  File "/Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/cogent/app/util.py", line 251, in __call__
    open(errfile).read())
cogent.app.util.ApplicationError: Unacceptable application exit status: 1
Command:
cd "/Users/mortonjt/Documents/CUBio/AmericanGut/workspace/mislabel/"; R --slave --no-restore --args --source_dir /Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/qiime-1.8.0_dev-py2.7.egg/qiime/support_files/R -e oob -c BODY_SITE -m "data/combined_mapping.txt" -o "results" -n 500 -i "results/otu_table.txt" < /Users/mortonjt/.virtualenvs/qiime/lib/python2.7/site-packages/qiime-1.8.0_dev-py2.7.egg/qiime/support_files/R/randomforests.r > "/tmp/tmpbiz0pziv9BnQcFbHzfef.txt" 2> "/tmp/tmpwBYW93EXGoTTXNWxNp6w.txt"
StdOut:

StdErr:
Warning message:
package ‘optparse’ was built under R version 3.1.2 
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 204 did not have 298 elements
Calls: load.qiime.mapping.file -> read.qiime.table -> read.table -> scan
Execution halted
```

I have no problems parsing this file using pandas at all.

**Comment by jairideout** [comment]
Can you try validating it with `validate_mapping_file.py`? The R mapping file parser is pretty picky, but if you fix all errors and warnings it should work.

**Comment by mortonjt** [comment]
Had a really hard time running `validate_mapping_file.py` - it was taking a really long time on my mapping file.  I can try that out to see if it'll fix that error

I ended up applying `cut` and only grabbing the columns that I needed, by @wasade 's recommendation.  That seemed to have worked.

**Comment by jairideout** [comment]
Cool, glad you have a workaround! I'm going to close this because another issue exists to improve the R mapping file parser and its cryptic error messages (#1804).

**Comment by wasade** [comment]
One reason to keep this open is due to the scalability issues with
`validate_mapping_file.py`. Is it expected that it should handle AG sized
metadata (approx 5000 x 150)?

**Comment by jairideout** [comment]
Can you please create a new issue that clearly identifies this problem? The issue title and a lot of the discussion here isn't related to validate_mapping_file.py's scalability issues.

**Comment by wasade** [comment]
Done

**Comment by jairideout** [comment]
Thanks!
