### ISSUE TITLE
Adonis in compare_categories.py fails where Description field in mapping file is empty

### ISSUE THREAD

**Issue by greggiceton** [biocore/qiime#2054]
Hello all.  If the mandatory Description field in the mapping file is left empty, the compare_categories.py script throws the following error where the method is adonis.

Traceback (most recent call last):
  File "/home/a4105038/qiime_software/qiime-1.7.0-release/bin/compare_categories.py", line 184, in <module>
    main()
  File "/home/a4105038/qiime_software/qiime-1.7.0-release/bin/compare_categories.py", line 180, in main
    categories, opts.num_permutations, out_dir)
  File "/home/a4105038/qiime_software/qiime-1.7.0-release/lib/qiime/compare_categories.py", line 130, in compare_categories
    rex(command_args, '%s.r' % method, output_dir=out_dir)
  File "/home/a4105038/qiime_software/qiime-1.7.0-release/lib/qiime/util.py", line 1990, in __call__
    %(''.join(open(errfilepath,'r').readlines()))
cogent.app.util.ApplicationError: Unacceptable application exit status: 1, command: cd "/home/a4105038/Documents/NGS_data/DNAComp/";  R --slave --args --source_dir /home/a4105038/qiime_software/qiime-1.7.0-release/lib/qiime/support_files/R -d /home/a4105038/Documents/NGS_data/DNAComp/beta_div_sil/unweighted_unifrac_otu_table_non_chimeric_sil.txt -m /home/a4105038/Documents/NGS_data/DNAComp/DNACompmap.txt -c Method -o /home/a4105038/Documents/NGS_data/DNAComp/cat_sig_adonis -n 999  < /home/a4105038/qiime_software/qiime-1.7.0-release/lib/qiime/support_files/R/adonis.r Program output: 

Error in model.frame.default(formula, data, drop.unused.levels = TRUE) : 
  invalid type (NULL) for variable 'qiime.data$map[[opts$category]]'
Calls: adonis -> model.frame -> model.frame.default
Execution halted

**Comment by ETaSky** [comment]
exact same issue here in QIIME 1.9.1. Have you figured it out yet? I guess it is related to the category of mapping file.

**Comment by ETaSky** [comment]
OK, just found a solution mentioned in on google group post. Fill all empty space in the mapping file with NA (or something). Mine used to have those Description, Barcode stuffs, empty.

**Comment by gregcaporaso** [comment]
Yes, sorry for the trouble, we'll be removing many of these fields that are required but not always actually used in QIIME 2 to make generation of mapping files simpler.
