### ISSUE TITLE
error on assign_taxonomy.py 

### ISSUE THREAD

**Issue by wentyqq** [biocore/qiime#2058]
I did the taxonomy assignment using local RDP database,but encountered the following error. The sad thing is I am not familiar with python script.  Can Someone help me! 

Traceback (most recent call last):
  File "/usr/local/bin/assign_taxonomy.py", line 5, in <module>
    pkg_resources.run_script('qiime==1.9.0', 'assign_taxonomy.py')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/qiime-1.9.0-py2.7.egg/EGG-INFO/scripts/assign_taxonomy.py", line 417, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/qiime-1.9.0-py2.7.egg/EGG-INFO/scripts/assign_taxonomy.py", line 394, in main
    log_path=log_path)
  File "/usr/local/lib/python2.7/dist-packages/qiime-1.9.0-py2.7.egg/qiime/assign_taxonomy.py", line 859, in __call__
    max_memory=max_memory, tmp_dir=tmp_dir)
  File "/usr/local/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 515, in train_rdp_classifier_and_assign_taxonomy
    tmp_dir=tmp_dir)
  File "/usr/local/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 485, in train_rdp_classifier
    return app(training_seqs_file)
  File "/usr/local/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 327, in __call__
    remove_tmp=remove_tmp)
  File "/usr/local/lib/python2.7/dist-packages/burrito-0.9.0-py2.7.egg/burrito/util.py", line 284, in __call__
    'StdErr:\n%s\n' % open(errfile).read())
burrito.util.ApplicationError: Unacceptable application exit status: 1

**Comment by drish91** [comment]
Did this ever get answered? I'm getting a similar error and am not sure how to proceed!

**Comment by zhaov1** [comment]
Did this ever get answered? I'm getting a similar error and am not sure how to proceed!
