### ISSUE TITLE
filter_samples_from_otu_table.py error possibly related to hdf5 (missing) format?

### ISSUE THREAD

**Issue by natassagioti** [biocore/qiime#2065]
Hi,
I have a problem with the filter_samples_from_otu_table.py command that may be related to the biom format,and which I cannot solve:
I am using MacQiime 1.9, and  try to filter my samples based on the number of counts or by providing a file containing the samples to exclude and get the same error :

filter_samples_from_otu_table.py -i TrimmedSortedTaxa_Fullhdf5.otu_table.biom -o Filtered/TrimmedSortedTaxaFull.otu_table-f.biom --output_mapping_fp=Filtered/mapping_file_forEdited-f.txt -m mapping_file_forEdited.txt --sample_id_fp=samples-tofilterout.txt --negate_sample_id_fp

Traceback (most recent call last):
  File "/macqiime/anaconda/bin/filter_samples_from_otu_table.py", line 162, in <module>
    main()
  File "/macqiime/anaconda/bin/filter_samples_from_otu_table.py", line 138, in main
    write_biom_table(filtered_otu_table, output_fp)
  File "/macqiime/anaconda/lib/python2.7/site-packages/qiime/util.py", line 577, in write_biom_table
    biom_table.to_hdf5(biom_file, generated_by, compress)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3535, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3507, in axis_dump
    formatter[category](grp, category, md, compression)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 243, in general_formatter
    compression=compression)
  File "/macqiime/anaconda/lib/python2.7/site-packages/h5py/_hl/group.py", line 99, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/macqiime/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 60, in make_new_dset
    raise ValueError("Shape tuple is incompatible with data")
ValueError: Shape tuple is incompatible with data

From the error message and a search on the internet (where i could not find much), I guessed this has to do with the format: My TrimmedSortedTaxaFull.otu_table.biom is in JSON format, and maybe this command somehow deals/tries to convert/expects an hdf5 one. Although I was told in the qiime forum that the scripts that accept biom files should automatically detect the format (https://groups.google.com/forum/#!topic/qiime-forum/WJ9tPQIhB-g), this looks like a bug (or something to do with my python libraries?)
I tried to circumvent the issue by converting to hdf5 and running the command again. Both commands below passed with no error, but the hdf5 file created is obviously problematic-it doesnot look like an hdf5 file, and I am not sure if there is an encoding issue this time:

biom convert -i TrimmedSortedTaxaFull.otu_table.txt -o TrimmedSortedTaxa_Fullhdf5.otu_table.biom --to-hdf5 --table-type="OTU table" --process-obs-metadata taxonomy -m mapping_file_forEdited.txt
filter_samples_from_otu_table.py -i TrimmedSortedTaxa_Fullhdf5.otu_table.biom -o Filtered/TrimmedSortedTaxaFull.otu_table-f.biom --output_mapping_fp=Filtered/mapping_file_forEdited-f.txt -m mapping_file_forEdited.txt --sample_id_fp=samples-tofilterout.txt --negate_sample_id_fp

Unfortunately, I cannot attach here any file other than image files, so that you can run yourselves and reproduce the error.
Can someone help?
Thanks in advance, 
Natassa

**Comment by natassagioti** [comment]
Two extra notes: 
First, my mapping file is OK:
validate_mapping_file.py -m Filtered/mapping_file_forEdited.txt 
No errors or warnings were found in mapping file.
(as well as a different version of it that I used below)
validate_mapping_file.py -m Filtered/mapping_file_forEdited-f-locations.txt -o Filtered/check_id_output/ 
No errors or warnings were found in mapping file.

Second, the created file supposedly in hdf5 format is not really a valid file, as I confirmed below:
split_otu_table.py -i Filtered/TrimmedSortedTaxaFull.otu_table-f.biom -m Filtered/mapping_file_forEdited-f-locations.txt -f Location -o Filtered/PerLocation/
Traceback (most recent call last):
  File "/macqiime/anaconda/bin/split_otu_table.py", line 165, in <module>
    main()
  File "/macqiime/anaconda/bin/split_otu_table.py", line 116, in main
    bt = load_table(biom_table_fp)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/parse.py", line 562, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: Filtered/TrimmedSortedTaxaFull.otu_table-f.biom does not appear to be a BIOM file!

**Comment by ElDeveloper** [comment]
Hi @natassagioti, this seems to be related to https://github.com/biocore/biom-format/issues/638, can you share your original BIOM file via Dropbox or something else? Additionally, how was this table generated?

**Comment by natassagioti** [comment]
Hi, 
Thanks for your answer! Yes, I have created a folder with some files and a README describing the commands used to generate them so that you can reproduce the error. Here:
https://www.dropbox.com/sh/4z67y4anz9dg1fb/AADoeoASMLqRq5D2YAGFe9UEa?dl=0
I have to say that I no longer get the error that I pasted above for the split_otu_table.py command; when I was  converting the JSON file to txt and before converting to hdf5, I had edited the txt file to delete the first line (irrational behavior of me!)-when I don't do this, the hdf5 file created can pass the split command.
Still, I am very suspicious of this hdf5 file, which really doesnot seem like the ones described in the biom format pages. So i am not sure whether i won't face new problems in my future commands.
Thank you, 
Natassa

**Comment by ElDeveloper** [comment]
@natassagioti, thanks a lot for sending these commands and files, they are very useful! I was able to reproduce the problem in my machine. Note that while your workaround seems to be working you are losing the `'ConfScore'` metadata.

How was your JSON table generated?

**Comment by natassagioti** [comment]
I know that these metadata are lost.. And this is why I am asking if this hdf5 file is really an hdf5 one, because I might need to add back the data and the command might fail. What do you think? When I open it in an Editor it looks very weird, but maybe this is just the encoding? qiime doesnot complain when I use it to split etc, though. And what about the initial error? I would prefer to use the json file for all analyses.
The data were generated from a usearch pipeline that the company we did the 16S sequencing uses. It has taken me quite a while to communicate with them on what exactly the pipeline does, and I still do not have the full image or the exact commands for all steps. Is there some specific part of the analysis  you are interested in? I can send you their methodology pdf, although this is vague (I got more answers from emailing). In any case, I spent some time on these otu tables and other files to make them compatible with qiime and I thought they were, but since it is the first time I do this type of analysis, I might be wrong. 
Any ideas on where the bug comes from?
Many thanks, 
Natassa

**Comment by ElDeveloper** [comment]
Thanks for the info, to clarify, yes it is an HDF5 file, is a valid
BIOM-formatted HDF5 file, the reason why it looks like gibberish when
you open it in a text editor is because HDF5 is a binary file
specification thus not generally easy to read for humans but easier to
read for machines.

I was wondering about the origin of the file because it is the first
time I see that kind of observation metadata. It's regrettable that we
have that bug in the BIOM format, but if you are not planning on using
that additional metadata, then you should be good to go. The bug is
entirely coming from the BIOM format and the way it deals with metadata:
https://github.com/biocore/biom-format/issues/638
