### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by hackerzone85** [biocore/qiime#2071]
```javascript
[usr@blab NGS_Data]$ pick_de_novo_otus.py -i SO-3576-MK1_RUN1.fastq -o $PWD/derep_uc/ -p dereplication_params.txt
Traceback (most recent call last):
  File "/usr/bin/pick_de_novo_otus.py", line 5, in <module>
    pkg_resources.run_script('qiime==1.9.1', 'pick_de_novo_otus.py')
  File "/usr/lib/python2.7/site-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/EGG-INFO/scripts/pick_de_novo_otus.py", line 180, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/EGG-INFO/scripts/pick_de_novo_otus.py", line 147, in main
    option_parser)
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/qiime/workflow/util.py", line 156, in validate_and_set_jobs_to_start
    if (jobs_to_start != int(default_jobs_to_start)) and \
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by colinbrislawn** [comment]
@hackerzone85 
Can you post the file `dereplication_params.txt`? I think you have messed up an input parameter. 

(P.S. For questions about parameters and general troubleshooting, the [qiime-forum](https://groups.google.com/forum/#!forum/qiime-forum) may be a better fit than github issues. For one thing, we answers questions much more quickly on the forum :smile: )

**Comment by gregcaporaso** [comment]
Yes, this is more of a forum-style question.
