### ISSUE TITLE
plot_taxa_summary.py will fail with matplotlib 1.5.0

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#2117]
The Jenkins build is failing, for the most part due to the following error:

```
Stderr
Traceback (most recent call last):
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/bin/plot_taxa_summary.py", line 278, in <module>
    main()
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/bin/plot_taxa_summary.py", line 274, in main
    resize_nth_label, label_type, include_html_legend)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 1138, in make_all_charts
    resize_nth_label, label_type, include_html_legend))
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 1073, in get_counts
    label_type, include_html_legend))
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 861, in make_HTML_table
    props={'title': title})
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 662, in make_area_bar_chart
    background_color, img_abs, generate_image_type, dpi)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 187, in make_legend
    shadow=False, fancybox=False)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/figure.py", line 1251, in legend
    l = Legend(self, handles, labels, *args, **kwargs)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend.py", line 385, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend.py", line 654, in _init_legend_box
    fontsize, handlebox))
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend_handler.py", line 119, in legend_artist
    fontsize, handlebox.get_transform())
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend_handler.py", line 252, in create_artists
    self.update_prop(p, orig_handle, legend)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend_handler.py", line 78, in update_prop
    legend._set_artist_props(legend_handle)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/legend.py", line 401, in _set_artist_props
    a.set_figure(self.figure)
  File "/mnt/workspace/QIIME/anaconda/envs/test_env/lib/python2.7/site-packages/matplotlib/artist.py", line 640, in set_figure
    raise RuntimeError("Can not put single artist in "
RuntimeError: Can not put single artist in more than one figure
```
This is the reason why #2115 is failing.

From [this post in the QIIME forum](https://groups.google.com/forum/#!topic/qiime-forum/x_ANVSoweq8), it seems like this is a problem that can be solved by downgrading matplotlib to something <1.5.0.

Not sure exactly what we want to do with this.

**Comment by colinbrislawn** [comment]
and another one:
https://groups.google.com/d/msg/qiime-forum/8VopZ3AOmms/aPVMUqTQAwAJ

>pip install 'matplotlib==1.4.3' solved my issue.

**Comment by wasade** [comment]
Just to comment, this was also a problem with the workshop I'm doing as the install for QIIME worked until testing the tutorial. Due to the nature of the workshop, we weren't able to reuse the QIIME AMI so it was a fresh install that was impacted.

**Comment by gregcaporaso** [comment]
Should we just set the version requirement to ``1.4.3`` in ``setup.py``?

**Comment by ElDeveloper** [comment]
I think that is the easiest, alternative is to fix the code to work with
the current API and make sure it's a backwards compatible change.

**Comment by metaltree99** [comment]
We are experiencing the same issue. Sorry, but from your last posts, it is not clear to me how to proceed to fix it, could you explain it to me?

**Comment by ElDeveloper** [comment]
`pip install 'matplotlib==1.4.3'` running this command should make your installation functional.

**Comment by metaltree99** [comment]
Thanks, that solved it!

**Comment by billyfournier** [comment]
Thanks for this. I was having the same issue. I still an error, but it appears to be working.

This is the error:
/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):

**Comment by ElDeveloper** [comment]
No need to worry about that, this is a warning, so you can safely ignore
this.

**Comment by tacaswell** [comment]
This error is a sign that you are doing something kind of sketchy in your plotting.  This is a semi-intentional break because what you are doing is probably not _really_ working (and if it seems like it is it is coincidence).

**Comment by colinbrislawn** [comment]
Hi @tacaswell. Thanks for contributing to matplotlib and advising us on this issue.

Would you be willing to take a look the example plots on this page and see if you notice anything fishy about them that could be related to this error?
http://qiime.org/1.2.1/tutorials/taxonomy_summaries.html#id3 

Thank you!
