### ISSUE TITLE
validate_mapping_file.py failed with sckit-bio 0.4.0

### ISSUE THREAD

**Issue by homopolymer** [biocore/qiime#2119]
Run validate_mapping_file.py -h, but get the following errors:

Traceback (most recent call last):
    File "/home/ubuntu/anaconda2/bin/validate_mapping_file.py", line 14, in <module>
        from qiime.util import parse_command_line_parameters, get_options_lookup,\
    File "/home/ubuntu/anaconda2/bin/lib/python2.7/site-packages/qiime/util.py", line 50, in <module>
        from skbio.format.sequences import format_fastq_record
ImportError: No module named format.sequences

====================================

The version of Scikit-Bio in my own system is 0.4.0.

**Comment by mortonjt** [comment]
Hi @homopolymer .  Qiime is actually not compatible with scikit-bio 0.4.0.  Try downgrading scikit-bio to 0.2.3
