### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by wasade** [biocore/qiime#2123]
Bit surprised to see this. It's running on an EC2 instance (not the QIIME AMI). QIIME was installed via pip and is using matplotlib 1.4.3. This is on `core_diversity_analysis.py`:

```python
/home/genomics/miniconda2/lib/python2.7/site-packages/skbio/stats/ordination/_principal_coordinate_analysis.py:107: RuntimeWarning: The result contains negative eigenvalues. Please compare their magnitude with the magnitude of some of the largest positive eigenvalues. If the negative ones are smaller, it's probably safe to ignore them, but if they are large in magnitude, the results won't be useful. See the Notes section for more details. The smallest eigenvalue is -0.0331688516712 and the largest is 4.57221502929.
  RuntimeWarning
Traceback (most recent call last):
  File "/home/genomics/miniconda2/bin/core_diversity_analyses.py", line 202, in <module>
    main()
  File "/home/genomics/miniconda2/bin/core_diversity_analyses.py", line 199, in main
    status_update_callback=status_update_callback)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/qiime/workflow/core_diversity_analyses.py", line 327, in run_core_diversity_analyses
    retain_intermediate_files=False)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/qiime/workflow/downstream.py", line 342, in run_alpha_rarefaction
    close_logger_on_success=close_logger_on_success)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/qiime/workflow/util.py", line 122, in call_commands_serially
    raise WorkflowError(msg)
qiime.workflow.util.WorkflowError: 

*** ERROR RAISED DURING STEP: Rarefaction plot: All metrics
Command run was:
 make_rarefaction_plots.py -i cdout//arare_max1114//alpha_div_collated/ -m map.tsv -o cdout//arare_max1114//alpha_rarefaction_plots/ 
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/home/genomics/miniconda2/bin/make_rarefaction_plots.py", line 229, in <module>
    main()
  File "/home/genomics/miniconda2/bin/make_rarefaction_plots.py", line 219, in main
    generate_average_tables=generate_average_tables)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/qiime/make_rarefaction_plots.py", line 667, in make_averages
    metric_name, output_type)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/qiime/make_rarefaction_plots.py", line 36, in save_ave_rarefaction_plots
    plt.clf()
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 547, in clf
    gcf().clf()
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 462, in gcf
    return figure()
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/genomics/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/home/genomics/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by mortonjt** [comment]
I think that is a matplotlib error. Looks like there is a workaround by
modifying the .matplotlibrc as shown below

https://groups.google.com/forum/#!searchin/qiime-forum/no$20$24DISPLAY$20/qiime-forum/6srHDScyh_0/yVJQfjo1V-EJ

**Comment by wasade** [comment]
There hasn't previously been a need to have a matplotibrc to run qiime...

**Comment by gregcaporaso** [comment]
Yeah, we've never had to have matplotlibrc before. Note that in the QIIME AMI we install ``apt-get install tcl-dev`` - could that be related? The steps that we take to build the QIIME AMI are [here](https://github.com/biocore/qiime/wiki/Building-the-QIIME-AMI).

**Comment by jairideout** [comment]
We are creating a matplotlibrc file when building the AMI, see step 8.

**Comment by wasade** [comment]
:/ much more complex than "pip install numpy; pip install qiime"

Thanks, I think this can be closed

**Comment by gregcaporaso** [comment]
Thanks @jairideout, missed that step. 

@wasade, yep, QIIME 2 time...
