### ISSUE TITLE
Align_seqs error help please! New user here

### ISSUE THREAD

**Issue by opizz** [biocore/qiime#2131]
Hi there,
I'm new at this and any help with this error would be greatly appreciated! Not sure how to even start...looks like it's looking for a temporary directory. Any insight would be greatly appreciated!!

Running alignment on node and after running for over an hour and a half, it returns this error:

 Traceback (most recent call last):
  File "/home/qiime/qiime_software/qiime-1.8.0-release/bin/align_seqs.py", line 204, in <module>
    main()
  File "/home/qiime/qiime_software/qiime-1.8.0-release/bin/align_seqs.py", line 187, in main
    log_path=log_path,failure_path=failure_path)
  File "/home/qiime/qiime_software/qiime-1.8.0-release/lib/qiime/align_seqs.py", line 261, in __call__
    temp_dir=get_qiime_temp_dir())
  File "/home/qiime/qiime_software/pynast-1.2.2-release/lib/python2.7/site-packages/pynast/util.py", line 812, in pynast_seqs
    for seq, status in pynast_iterator:
  File "/home/qiime/qiime_software/pynast-1.2.2-release/lib/python2.7/site-packages/pynast/util.py", line 651, in ipynast_seqs
    current_result = pw_alignment_iterator.next()
  File "/home/qiime/qiime_software/pynast-1.2.2-release/lib/python2.7/site-packages/pynast/pycogent_backports/uclust.py", line 411, in uclust_search_and_align_from_fasta_filepath
    app_result = app(input_data)
  File "/home/qiime/qiime_software/pycogent-1.5.3-release/lib/python2.7/site-packages/cogent/app/util.py", line 250, in __call__
    open(outfile).read(), 
IOError: [Errno 2] No such file or directory: '/tmp/tmp7dCUXVqOzqmGGgLpg0vF.txt'

Thanks!

**Comment by colinbrislawn** [comment]
Hi @opizz, thanks for getting in touch with us!

Can you post this question over at the [Qiime Forums](https://groups.google.com/forum/#!forum/qiime-forum)? I'm guessing this is an issue with the /tmp/ directory on your Qiime VM, I think we can probably answer it faster on the forums. Github is usually a better fit for fixing bugs or adding features. 

Thanks!
Colin B
