### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pathlib2.py

### ISSUE THREAD

**Issue by Wnegara** [biocore/qiime#2146]
Hi, I have installed qiime in my windows 10 using Oracle VM virtual box without any problem. However, the problem come when I tried to upgrade the pip or install Jupyter notebook with error code no 13. Anyone can help me sort out this problem? thanks.

Here the conversation that I got from the terminal for pip upgrade:
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/basecommand.py", line 232, in main
          status = self.run(options, args)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/commands/install.py", line 347, in run
          root=options.root_path,
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_set.py", line 543, in install
          requirement.uninstall(auto_confirm=True)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 667, in uninstall
          paths_to_remove.remove(auto_confirm)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_uninstall.py", line 126, in remove
          renames(path, new_path)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/utils/__init__.py", line 316, in renames
          shutil.move(old, new)
        File "/usr/lib/python2.7/shutil.py", line 297, in move
          rmtree(src)
        File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
          rmtree(fullname, ignore_errors, onerror)
        File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
          onerror(os.remove, fullname, sys.exc_info())
        File "/usr/lib/python2.7/shutil.py", line 248, in rmtree
          os.remove(fullname)
      OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/EGG-INFO/top_level.txt'

**Comment by gregcaporaso** [comment]
Hello, would you mind reposting your question to the [QIIME Forum](http://forum.qiime.org)? We try to consolidate these types of questions there. Thank you!
