### ISSUE TITLE
differential_abundance.py error

### ISSUE THREAD

**Issue by hotblast** [biocore/qiime#2147]
I got this error when i was trying to run differential_abundance.py. I have no problem of running a similar command --group_significance.py. Any insight? Many thanks--Gary

[147760@seq-fe4 IBD]$ differential_abundance.py -i QIIME.KO.function.data.biom  -o QIIME.KO.Function_diff_otus.txt -m mapping.txt  -a metagenomeSeq_fitZIG -c Treatment -x IBD  -y HEA
Traceback (most recent call last):
  File "/scratch-218819/apps/anaconda2/bin/differential_abundance.py", line 159, in <module>
    main()
  File "/scratch-218819/apps/anaconda2/bin/differential_abundance.py", line 142, in main
    DA_fitZIG(input_path, out_path, mapping_fp, mapping_category, subcategory_1, subcategory_2)
  File "/scratch-218819/apps/anaconda2/lib/python2.7/site-packages/qiime/differential_abundance.py", line 58, in DA_fitZIG
    suffix='.biom') as temp_fh:
  File "/scratch-218819/apps/anaconda2/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/scratch-218819/apps/anaconda2/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/tmp/147760/QIIME-differential-abundance-temp-table-vVnq5H.biom'

**Comment by gregcaporaso** [comment]
Hello, would you mind reposting your question to the [QIIME Forum](http://forum.qiime.org)? We try to consolidate these types of questions there. Thank you!
