### ISSUE TITLE
I have Plugin error from demux

### ISSUE THREAD

**Issue by hulqi** [biocore/qiime#2200]
(qiime2-2017.7) [user@smp1 qiime2-moving-pictures-tutorial]$ qiime demux summarize --i-data demux.qza --o-visualization demux.qzv

Plugin error from demux:

  Invalid DISPLAY variable

Debug info has been saved to /tmp/qiime2-q2cli-err-0ct5ly96.log.

#######/tmp/qiime2-q2cli-err-0ct5ly96.log#############
Traceback (most recent call last):
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/q2cli/commands.py", line 222, in __call__
    results = action(**arguments)
  File "<decorator-gen-179>", line 2, in summarize
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/qiime2/sdk/action.py", line 201, in callable_wrapper
    output_types, provenance)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/qiime2/sdk/action.py", line 392, in _callable_executor_
    ret_val = callable(output_dir=temp_dir, **view_args)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/q2_demux/_summarize/_visualizer.py", line 162, in summarize
    ax = sns.distplot(result, kde=False)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/seaborn/distributions.py", line 161, in distplot
    ax = plt.gca()
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/public/agis/gaofei_group/huqi/01_software/opt/Miniconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
############################################################################

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 2 forum](http://forum.qiime2.org)? That's where we provide user support for QIIME 2 (note that this is the QIIME 1 issue tracker).
