### ISSUE TITLE
Trying to convert txt. file to biom file

### ISSUE THREAD

**Issue by Acetylcholine88** [biocore/qiime#2204]
Can someone help?

Tried the following command:

biom convert -i OTU_original.txt -o OTU_original.biom --table-type "OTU table" --to-hdf5 --process-obs-metadata taxonomy

this is what I got:

biom convert: error: option -i: file does not exist: 'OTU.txt'

-bash-4.2$ biom convert -i OTU_original.txt -o OTU_original.biom --table-type "OTU table" --process-obs-metadata taxonomy

Traceback (most recent call last):

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/bin/pyqi", line 4, in <module>

    __import__('pkg_resources').run_script('pyqi==0.3.2', 'pyqi')

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 738, in run_script

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1499, in run_script

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/EGG-INFO/scripts/pyqi", line 184, in <module>

    optparse_main(cmd_obj, argv[1:])

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main

    result = optparse_cmd(local_argv[1:])

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interface.py", line 39, in __call__

    cmd_result = self.CmdInstance(**cmd_input)

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/command.py", line 137, in __call__

    result = self.run(**kwargs)

  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/biom/commands/table_converter.py", line 217, in run

    raise CommandError(convert_error_msg)

pyqi.core.exception.CommandError: Input does not look like a classic table. Did you forget to specify that a classic table file should be created from a BIOM table file?

Help would be very much appreciated - I am super lost!

[test.xlsx](https://github.com/biocore/qiime/files/1408523/test.xlsx)

**Comment by jairideout** [comment]
Can you post this on the [biom-format issue tracker](https://github.com/biocore/biom-format/issues)?
 Thanks!
