### ISSUE TITLE
Error constructing CommandLineAppResult - assign_taxonomy.py

### ISSUE THREAD

**Issue by KeironO** [biocore/qiime#2208]
Command:
````
assign_taxonomy.py -i rep_set.fna -o assigned_taxonomy -t /home/shared/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt -r /home/shared/gg_13_8_otus/rep_set/97_otus.fasta -m sortmerna
````

Returns 

```
Traceback (most recent call last):
  File "/usr/local/bin/assign_taxonomy.py", line 417, in <module>
    main()
  File "/usr/local/bin/assign_taxonomy.py", line 390, in main
    log_path=log_path)
  File "/usr/local/lib/python2.7/dist-packages/qiime/assign_taxonomy.py", line 343, in __call__
    HALT_EXEC=False)
  File "/usr/local/lib/python2.7/dist-packages/bfillings/sortmerna_v2.py", line 542, in sortmerna_map
    app_result = smr()
  File "/usr/local/lib/python2.7/dist-packages/burrito/util.py", line 303, in __call__
    result_paths)
  File "/usr/local/lib/python2.7/dist-packages/burrito/util.py", line 325, in _handle_app_result_build_failure
    raise ApplicationError("Error constructing CommandLineAppResult.")
burrito.util.ApplicationError: Error constructing CommandLineAppResult.
```

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support for QIIME 1.
