### ISSUE TITLE
Alpha_rarefraction.py error

### ISSUE THREAD

**Issue by santhoshnh** [biocore/qiime#2217]
Hello,
I am running alph_rarefraction.py for one of my sample. But i am getting an error. The Matrices generations running successfully. But  after that, alpha diveristy plots are not creating. it gives the below error

Traceback (most recent call last):
  File "/home/bgc/.conda/envs/qiime1/bin/alpha_rarefaction.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'alpha_rarefaction.py')
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/alpha_rarefaction.py", line 161, in <module>
    main()
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/alpha_rarefaction.py", line 158, in main
    retain_intermediate_files=retain_intermediate_files)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime/workflow/downstream.py", line 342, in run_alpha_rarefaction
    close_logger_on_success=close_logger_on_success)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime/workflow/util.py", line 122, in call_commands_serially
    raise WorkflowError(msg)
qiime.workflow.util.WorkflowError: 

*** ERROR RAISED DURING STEP: Rarefaction plot: All metrics
Command run was:
 make_rarefaction_plots.py -i arare/alpha_div_collated/ -m mappingfile.csv_corrected.txt -o arare/alpha_rarefaction_plots/ --background_color white --resolution 80 --imagetype png
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/home/bgc/.conda/envs/qiime1/bin/make_rarefaction_plots.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'make_rarefaction_plots.py')
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/make_rarefaction_plots.py", line 229, in <module>
    main()
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/make_rarefaction_plots.py", line 219, in main
    generate_average_tables=generate_average_tables)
  File "/home/bgc/.conda/envs/qiime1/lib/python2.7/site-packages/qiime/make_rarefaction_plots.py", line 578, in make_averages
    new_ymax = (max([max(v) for v in rares_data['series'].values()]) +
ValueError: max() arg is an empty sequence

Because of this error I stuck with my analysis. It will be more helpful for me, if you help me to solve this issue.

Thank you

**Comment by Samia741** [comment]
hello everyone, I am Samia. 
I am using QIIME1 and did all following steps before the alpha diversity.
But getting one error in the following stepalpha_rarefaction.py -i otus/otu_table.biom -m map_fluid_1.txt -o alpha_fluid_1 -p alpha_params.txt -t otus/rep_set.tre
My purpose is to get the OTU_table_Description.txt, sees_rep_set.fasta, taxa summary and PCoA.
I have tried many ways but cannot solve this problem in this step.
Please, help me.
