### ISSUE TITLE
Problems using count_seqs.py with joined reads

### ISSUE THREAD

**Issue by andso17** [biocore/qiime#2231]
I am pretty new to using these tools, so I hope I am not an inconvenience.

I am having problems with processing of an outputfile of joined reads, processed with the fastq-join from ea-utils. When running the following command I get an error, that seems to originate from failed import of files: 

count_seqs.py -i join

(here 'join' is the name of the file of the joined, paired reads generated via ea-utils)

The error message looks like this:

Traceback (most recent call last):
  File "/data/miniconda3/envs/qiime/bin/count_seqs.py", line 13, in <module>
    from qiime.util import (parse_command_line_parameters,
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/qiime/util.py", line 49, in <module>
    from skbio.util import remove_files, create_dir
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/__init__.py", line 15, in <module>
    import skbio.io
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/io/__init__.py", line 309, in <module>
    import_module('skbio.io.clustal')
  File "/data/miniconda3/envs/qiime/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/io/clustal.py", line 123, in <module>
    from skbio.alignment import Alignment
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/alignment/__init__.py", line 230, in <module>
    from ._alignment import Alignment, SequenceCollection, StockholmAlignment
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/alignment/_alignment.py", line 21, in <module>
    from skbio.stats.distance import DistanceMatrix
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/stats/distance/__init__.py", line 193, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/skbio/stats/distance/_base.py", line 17, in <module>
    from IPython.core.pylabtools import print_figure
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/data/miniconda3/envs/qiime/lib/python2.7/site-packages/decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                                            ^

I would be very grateful for any help on the matter

**Comment by andso17** [comment]
Sorry, the arrow (last line) is supposed to point at '='. Below the arrow, this error-message is printed: "SyntaxError: invalid syntax"
