### ISSUE TITLE
identify_chimeric_seqs.py path issue on some linux systems

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#289]
The following error gets produced if the user tries passing a relative filepath (file within the same folder the command is called) as the -a option "aligned_reference_seqs_fp". I have also provided a simple fix at the bottom of the description, however; it may not be the best way to handle it.

```
qiime@linux:/software/qiime-1.4.0-release/qiime_tutorial$ /software/qiime-1.4.0-release/scripts/identify_chimeric_seqs.py -i otus/pynast_aligned_seqs/seqs_rep_set_aligned.fasta -m ChimeraSlayer -a core_set_aligned.fasta.imputed -o test_chimera -v
Traceback (most recent call last):
    File "/software/qiime-1.4.0-release/scripts/identify_chimeric_seqs.py", line 172, in <module>
        main()
    File "/software/qiime-1.4.0-release/scripts/identify_chimeric_seqs.py", line 169, in main
        keep_intermediates=keep_intermediates)
    File "/software/qiime-1.4.0-release/lib/qiime/identify_chimeric_seqs.py", line 148, in chimeraSlayer_identify_chimeras
        keep_intermediates=keep_intermediates):
    File "/software/qiime-1.4.0-release/lib/qiime/identify_chimeric_seqs.py", line 133, in __call__
        keep_intermediates=keep_intermediates)
    File "/software/qiime-1.4.0-release/lib/qiime/identify_chimeric_seqs.py", line 592, in get_chimeras_from_Nast_aligned
        app_results = app()
    File "/software/pycogent-1.5.1-release/lib/python2.7/site-packages/cogent/app/util.py", line 269, in __call__
        result_paths=self._get_result_paths(data)) 
    File "/software/qiime-1.4.0-release/lib/qiime/identify_chimeric_seqs.py", line 405, in _get_result_paths
raise ApplicationError,"Calling ChimeraSlayer failed."
    cogent.app.util.ApplicationError: Calling ChimeraSlayer failed.
```

A simple fix for this is to make sure the "db_NAST" parameter is an absolute path using abspath. An example of a working fix would be changing lines 585-586 to the following:

```
params.update({'--db_NAST': abspath(ref_db_aligned_fp),'--db_FASTA': ref_db_fasta_fp})
```

**Comment by JackDarcy** [comment]
Hope this helps someone who is googling this problem. I had the same error message when using the absolute path for the aligned_reference_seqs_fp (-a) option of identify_chimeric_seqs.py. I fixed this by making a symbolic link to that file in my current directory:
    ln -s /usr/local/lib/python2.7/dist-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta ./
then running the script using that link. This fixed my issue (qiime version 1.9.1 on Ubuntu 16.04). It also might help people to know that you can find the absolute path of qiime's default pynast ref alignment with
    print_qiime_config.py | grep pynast_template_alignment_fp

-Jack
